Update to Deno 0.4.0
Fixes the following output

```
error: Found argument 'https://denopkg.com/syumai/deno-libs/denoinit/denoinit.ts' which wasn't expected, or isn't valid in this context

USAGE:
    deno [FLAGS] [OPTIONS] [SUBCOMMAND]

For more information try --help
```